routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


Route::group(['middleware' => 'auth:web',], function () {

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::resource('assesmentStudents', App\Http\Controllers\AssesmentStudentController::class);


    Route::resource('assesments', App\Http\Controllers\AssesmentController::class);


    Route::resource('batches', App\Http\Controllers\BatcheController::class);


    Route::resource('bracketStudents', App\Http\Controllers\BracketStudentController::class);


    Route::resource('brackets', App\Http\Controllers\BracketController::class);


    Route::resource('issueCategories', App\Http\Controllers\IssueCategoryController::class);


    Route::resource('issues', App\Http\Controllers\issueController::class);


    Route::resource('authors', App\Http\Controllers\AuthorController::class);


    Route::resource('bookAssigns', App\Http\Controllers\BookAssignController::class);


    Route::resource('books', App\Http\Controllers\BookController::class);


    Route::resource('genres', App\Http\Controllers\GenreController::class);


    Route::resource('publishers', App\Http\Controllers\PublisherController::class);


    Route::resource('academicYears', App\Http\Controllers\AcademicYearController::class);


    Route::resource('courses', App\Http\Controllers\CourseController::class);


    Route::resource('subjects', App\Http\Controllers\SubjectController::class);


    Route::resource('fees', App\Http\Controllers\FeeController::class);


    Route::resource('transactions', App\Http\Controllers\TransactionController::class);


    Route::resource('profiles', App\Http\Controllers\ProfileController::class);


    Route::resource('institutes', App\Http\Controllers\InstituteController::class);


    Route::resource('roles', App\Http\Controllers\RoleController::class);


    Route::resource('users', App\Http\Controllers\UserController::class);
});

app/Models/AcademicYear.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class AcademicYear
 * @package App\Models
 * @version December 18, 2021, 10:38 am UTC
 *
 * @property App\Models\Institute $institute
 * @property \Illuminate\Database\Eloquent\Collection $assesmentStudents
 * @property \Illuminate\Database\Eloquent\Collection $assesments
 * @property \Illuminate\Database\Eloquent\Collection $eduBatches
 * @property \Illuminate\Database\Eloquent\Collection $eduBracketStudents
 * @property \Illuminate\Database\Eloquent\Collection $eduBrackets
 * @property \Illuminate\Database\Eloquent\Collection $issues
 * @property \Illuminate\Database\Eloquent\Collection $masterCourses
 * @property \Illuminate\Database\Eloquent\Collection $masterSubjects
 * @property \Illuminate\Database\Eloquent\Collection $payFees
 * @property \Illuminate\Database\Eloquent\Collection $payTransactions
 * @property integer $institute_id
 * @property string $title
 * @property string $start_date
 * @property string $end_date
 */
class AcademicYear extends Model
{
    use SoftDeletes;


    public $table = 'master_academic_years';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'institute_id',
        'title',
        'start_date',
        'end_date'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'institute_id' => 'integer',
        'title' => 'string',
        'start_date' => 'date',
        'end_date' => 'date'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'institute_id' => 'required',
        'title' => 'required|string|max:255',
        'start_date' => 'required',
        'end_date' => 'required',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function institute()
    {
        return $this->belongsTo(\App\Models\Institute::class, 'institute_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function assesmentStudents()
    {
        return $this->hasMany(\App\Models\AssesmentStudent::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function assesments()
    {
        return $this->hasMany(\App\Models\Assesment::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function batches()
    {
        return $this->hasMany(\App\Models\Batch::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function bracketStudents()
    {
        return $this->hasMany(\App\Models\BracketStudent::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function brackets()
    {
        return $this->hasMany(\App\Models\Bracket::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function issues()
    {
        return $this->hasMany(\App\Models\Issue::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function masterCourses()
    {
        return $this->hasMany(\App\Models\Course::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    // public function masterSubjects()
    // {
    //     return $this->hasMany(\App\Models\Subject::class, 'academic_year_id');
    // }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function fees()
    {
        return $this->hasMany(\App\Models\PayFee::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function transactions()
    {
        return $this->hasMany(\App\Models\PayTransaction::class, 'academic_year_id');
    }
}

app/Http/Controllers/AcademicYearController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAcademicYearRequest;
use App\Http\Requests\UpdateAcademicYearRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\AcademicYear;
use Illuminate\Http\Request;
use Flash;
use Response;

class AcademicYearController extends AppBaseController
{
    /**
     * Display a listing of the AcademicYear.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var AcademicYear $academicYears */
        $academicYears = AcademicYear::paginate(10);

        return view('academic_years.index')
            ->with('academicYears', $academicYears);
    }

    /**
     * Show the form for creating a new AcademicYear.
     *
     * @return Response
     */
    public function create()
    {
        return view('academic_years.create');
    }

    /**
     * Store a newly created AcademicYear in storage.
     *
     * @param CreateAcademicYearRequest $request
     *
     * @return Response
     */
    public function store(CreateAcademicYearRequest $request)
    {
        $input = $request->all();

        /** @var AcademicYear $academicYear */
        $academicYear = AcademicYear::create($input);

        Flash::success('Academic Year saved successfully.');

        return redirect(route('academicYears.index'));
    }

    /**
     * Display the specified AcademicYear.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var AcademicYear $academicYear */
        $academicYear = AcademicYear::find($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        return view('academic_years.show')->with('academicYear', $academicYear);
    }

    /**
     * Show the form for editing the specified AcademicYear.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var AcademicYear $academicYear */
        $academicYear = AcademicYear::find($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        return view('academic_years.edit')->with('academicYear', $academicYear);
    }

    /**
     * Update the specified AcademicYear in storage.
     *
     * @param int $id
     * @param UpdateAcademicYearRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAcademicYearRequest $request)
    {
        /** @var AcademicYear $academicYear */
        $academicYear = AcademicYear::find($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        $academicYear->fill($request->all());
        $academicYear->save();

        Flash::success('Academic Year updated successfully.');

        return redirect(route('academicYears.index'));
    }

    /**
     * Remove the specified AcademicYear from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var AcademicYear $academicYear */
        $academicYear = AcademicYear::find($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        $academicYear->delete();

        Flash::success('Academic Year deleted successfully.');

        return redirect(route('academicYears.index'));
    }
}

resources/views/academic_years/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Academic Year</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'academicYears.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('academic_years.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('academicYears.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/academic_years/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Academic Year</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($academicYear, ['route' => ['academicYears.update', $academicYear->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('academic_years.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('academicYears.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/academic_years/fields.blade.php
<input type="hidden" name="institute_id" value="{{ institute('id') }}">
{{--
<!-- Institute Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('institute_id', 'Institute Id:') !!}
    {!! Form::number('institute_id', null, ['class' => 'form-control']) !!}
</div>
--}}

<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Start Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_date', 'Start Date:') !!}
    {!! Form::text('start_date', null, ['class' => 'form-control','id'=>'start_date']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#start_date').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- End Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('end_date', 'End Date:') !!}
    {!! Form::text('end_date', null, ['class' => 'form-control','id'=>'end_date']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#end_date').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

resources/views/academic_years/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Academic Years</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('academicYears.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('academic_years.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        @include('adminlte-templates::common.paginate', ['records' => $academicYears])
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/academic_years/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Academic Year Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('academicYears.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('academic_years.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/academic_years/show_fields.blade.php
<!-- Institute Id Field -->
<div class="col-sm-12">
    {!! Form::label('institute_id', 'Institute Id:') !!}
    <p>{{ $academicYear->institute_id }}</p>
</div>

<!-- Title Field -->
<div class="col-sm-12">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $academicYear->title }}</p>
</div>

<!-- Start Date Field -->
<div class="col-sm-12">
    {!! Form::label('start_date', 'Start Date:') !!}
    <p>{{ $academicYear->start_date }}</p>
</div>

<!-- End Date Field -->
<div class="col-sm-12">
    {!! Form::label('end_date', 'End Date:') !!}
    <p>{{ $academicYear->end_date }}</p>
</div>

resources/views/academic_years/table.blade.php
<div class="table-responsive">
    <table class="table" id="academicYears-table">
        <thead>
        <tr>
        <th>Title</th>
        <th>Start Date</th>
        <th>End Date</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($academicYears as $academicYear)
            <tr>
            <td>{{ $academicYear->title }}</td>
            <td>{{ $academicYear->start_date }}</td>
            <td>{{ $academicYear->end_date }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['academicYears.destroy', $academicYear->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('academicYears.show', [$academicYear->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('academicYears.edit', [$academicYear->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>