routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


Route::group(['middleware' => 'auth:web',], function () {

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::resource('assesmentStudents', App\Http\Controllers\AssesmentStudentController::class);


    Route::resource('assesments', App\Http\Controllers\AssesmentController::class);


    Route::resource('batches', App\Http\Controllers\BatcheController::class);


    Route::resource('bracketStudents', App\Http\Controllers\BracketStudentController::class);


    Route::resource('brackets', App\Http\Controllers\BracketController::class);


    Route::resource('issueCategories', App\Http\Controllers\IssueCategoryController::class);


    Route::resource('issues', App\Http\Controllers\issueController::class);


    Route::resource('authors', App\Http\Controllers\AuthorController::class);


    Route::resource('bookAssigns', App\Http\Controllers\BookAssignController::class);


    Route::resource('books', App\Http\Controllers\BookController::class);


    Route::resource('genres', App\Http\Controllers\GenreController::class);


    Route::resource('publishers', App\Http\Controllers\PublisherController::class);


    Route::resource('academicYears', App\Http\Controllers\AcademicYearController::class);


    Route::resource('courses', App\Http\Controllers\CourseController::class);


    Route::resource('subjects', App\Http\Controllers\SubjectController::class);


    Route::resource('fees', App\Http\Controllers\FeeController::class);


    Route::resource('transactions', App\Http\Controllers\TransactionController::class);


    Route::resource('profiles', App\Http\Controllers\ProfileController::class);


    Route::resource('institutes', App\Http\Controllers\InstituteController::class);


    Route::resource('roles', App\Http\Controllers\RoleController::class);


    Route::resource('users', App\Http\Controllers\UserController::class);
});

app/Models/BracketStudent.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class BracketStudent
 * @package App\Models
 * @version December 18, 2021, 10:37 am UTC
 *
 * @property \App\Models\MasterAcademicYear $academicYear
 * @property \App\Models\Batch $batch
 * @property \App\Models\Bracket $bracket
 * @property \App\Models\MasterCourse $course
 * @property App\Models\Institute $institute
 * @property \App\Models\User $student
 * @property \App\Models\MasterSubject $subject
 * @property \App\Models\User $teacher
 * @property integer $institute_id
 * @property integer $academic_year_id
 * @property integer $course_id
 * @property integer $batch_id
 * @property integer $bracket_id
 * @property integer $teacher_id
 * @property integer $subject_id
 * @property integer $student_id
 * @property boolean $status
 * @property string $review
 */
class BracketStudent extends Model
{
    use SoftDeletes;


    public $table = 'edu_bracket_students';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'institute_id',
        'academic_year_id',
        'course_id',
        'batch_id',
        'bracket_id',
        'teacher_id',
        'subject_id',
        'student_id',
        'status',
        'review'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'institute_id' => 'integer',
        'academic_year_id' => 'integer',
        'course_id' => 'integer',
        'batch_id' => 'integer',
        'bracket_id' => 'integer',
        'teacher_id' => 'integer',
        'subject_id' => 'integer',
        'student_id' => 'integer',
        'status' => 'boolean',
        'review' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'institute_id' => 'required',
        'academic_year_id' => 'required',
        'course_id' => 'required',
        'batch_id' => 'required',
        'bracket_id' => 'required',
        'teacher_id' => 'required',
        'subject_id' => 'required',
        'student_id' => 'required',
        'status' => 'required|boolean',
        'review' => 'nullable|string',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function academicYear()
    {
        return $this->belongsTo(\App\Models\AcademicYear::class, 'academic_year_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function batch()
    {
        return $this->belongsTo(\App\Models\Batch::class, 'batch_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function bracket()
    {
        return $this->belongsTo(\App\Models\Bracket::class, 'bracket_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function course()
    {
        return $this->belongsTo(\App\Models\Course::class, 'course_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function institute()
    {
        return $this->belongsTo(\App\Models\Institute::class, 'institute_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function student()
    {
        return $this->belongsTo(\App\Models\User::class, 'student_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function subject()
    {
        return $this->belongsTo(\App\Models\Subject::class, 'subject_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function teacher()
    {
        return $this->belongsTo(\App\Models\User::class, 'teacher_id');
    }
}

app/Http/Controllers/BracketStudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBracketStudentRequest;
use App\Http\Requests\UpdateBracketStudentRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\BracketStudent;
use Illuminate\Http\Request;
use Flash;
use Response;

class BracketStudentController extends AppBaseController
{
    /**
     * Display a listing of the BracketStudent.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var BracketStudent $bracketStudents */
        $bracketStudents = BracketStudent::paginate(10);

        return view('bracket_students.index')
            ->with('bracketStudents', $bracketStudents);
    }

    /**
     * Show the form for creating a new BracketStudent.
     *
     * @return Response
     */
    public function create()
    {
        return view('bracket_students.create');
    }

    /**
     * Store a newly created BracketStudent in storage.
     *
     * @param CreateBracketStudentRequest $request
     *
     * @return Response
     */
    public function store(CreateBracketStudentRequest $request)
    {
        $input = $request->all();

        /** @var BracketStudent $bracketStudent */
        $bracketStudent = BracketStudent::create($input);

        Flash::success('Bracket Student saved successfully.');

        return redirect(route('bracketStudents.index'));
    }

    /**
     * Display the specified BracketStudent.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var BracketStudent $bracketStudent */
        $bracketStudent = BracketStudent::find($id);

        if (empty($bracketStudent)) {
            Flash::error('Bracket Student not found');

            return redirect(route('bracketStudents.index'));
        }

        return view('bracket_students.show')->with('bracketStudent', $bracketStudent);
    }

    /**
     * Show the form for editing the specified BracketStudent.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var BracketStudent $bracketStudent */
        $bracketStudent = BracketStudent::find($id);

        if (empty($bracketStudent)) {
            Flash::error('Bracket Student not found');

            return redirect(route('bracketStudents.index'));
        }

        return view('bracket_students.edit')->with('bracketStudent', $bracketStudent);
    }

    /**
     * Update the specified BracketStudent in storage.
     *
     * @param int $id
     * @param UpdateBracketStudentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBracketStudentRequest $request)
    {
        /** @var BracketStudent $bracketStudent */
        $bracketStudent = BracketStudent::find($id);

        if (empty($bracketStudent)) {
            Flash::error('Bracket Student not found');

            return redirect(route('bracketStudents.index'));
        }

        $bracketStudent->fill($request->all());
        $bracketStudent->save();

        Flash::success('Bracket Student updated successfully.');

        return redirect(route('bracketStudents.index'));
    }

    /**
     * Remove the specified BracketStudent from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var BracketStudent $bracketStudent */
        $bracketStudent = BracketStudent::find($id);

        if (empty($bracketStudent)) {
            Flash::error('Bracket Student not found');

            return redirect(route('bracketStudents.index'));
        }

        $bracketStudent->delete();

        Flash::success('Bracket Student deleted successfully.');

        return redirect(route('bracketStudents.index'));
    }
}

resources/views/bracket_students/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Bracket Student</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'bracketStudents.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('bracket_students.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('bracketStudents.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/bracket_students/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Bracket Student</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($bracketStudent, ['route' => ['bracketStudents.update', $bracketStudent->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('bracket_students.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('bracketStudents.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/bracket_students/fields.blade.php
<input type="hidden" name="institute_id" value="{{ institute('id') }}">
{{--
<!-- Institute Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('institute_id', 'Institute Id:') !!}
    {!! Form::number('institute_id', null, ['class' => 'form-control']) !!}
</div>
--}}

<!-- Academic Year Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('academic_year_id', 'Academic Year Id:') !!}
    {!! Form::number('academic_year_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Course Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('course_id', 'Course Id:') !!}
    {!! Form::number('course_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Batch Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('batch_id', 'Batch Id:') !!}
    {!! Form::number('batch_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Bracket Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bracket_id', 'Bracket Id:') !!}
    {!! Form::number('bracket_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Teacher Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('teacher_id', 'Teacher Id:') !!}
    {!! Form::number('teacher_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Subject Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('subject_id', 'Subject Id:') !!}
    {!! Form::number('subject_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Student Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('student_id', 'Student Id:') !!}
    {!! Form::number('student_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    <div class="form-check">
        {!! Form::hidden('status', 0, ['class' => 'form-check-input']) !!}
        {!! Form::checkbox('status', '1', null, ['class' => 'form-check-input']) !!}
        {!! Form::label('status', 'Status', ['class' => 'form-check-label']) !!}
    </div>
</div>


<!-- Review Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('review', 'Review:') !!}
    {!! Form::textarea('review', null, ['class' => 'form-control','rows' => 2]) !!}
</div>

resources/views/bracket_students/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Bracket Students</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('bracketStudents.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('bracket_students.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        @include('adminlte-templates::common.paginate', ['records' => $bracketStudents])
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/bracket_students/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Bracket Student Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('bracketStudents.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('bracket_students.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bracket_students/show_fields.blade.php
<!-- Institute Id Field -->
<div class="col-sm-12">
    {!! Form::label('institute_id', 'Institute Id:') !!}
    <p>{{ $bracketStudent->institute_id }}</p>
</div>

<!-- Academic Year Id Field -->
<div class="col-sm-12">
    {!! Form::label('academic_year_id', 'Academic Year Id:') !!}
    <p>{{ $bracketStudent->academic_year_id }}</p>
</div>

<!-- Course Id Field -->
<div class="col-sm-12">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{{ $bracketStudent->course_id }}</p>
</div>

<!-- Batch Id Field -->
<div class="col-sm-12">
    {!! Form::label('batch_id', 'Batch Id:') !!}
    <p>{{ $bracketStudent->batch_id }}</p>
</div>

<!-- Bracket Id Field -->
<div class="col-sm-12">
    {!! Form::label('bracket_id', 'Bracket Id:') !!}
    <p>{{ $bracketStudent->bracket_id }}</p>
</div>

<!-- Teacher Id Field -->
<div class="col-sm-12">
    {!! Form::label('teacher_id', 'Teacher Id:') !!}
    <p>{{ $bracketStudent->teacher_id }}</p>
</div>

<!-- Subject Id Field -->
<div class="col-sm-12">
    {!! Form::label('subject_id', 'Subject Id:') !!}
    <p>{{ $bracketStudent->subject_id }}</p>
</div>

<!-- Student Id Field -->
<div class="col-sm-12">
    {!! Form::label('student_id', 'Student Id:') !!}
    <p>{{ $bracketStudent->student_id }}</p>
</div>

<!-- Status Field -->
<div class="col-sm-12">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $bracketStudent->status }}</p>
</div>

<!-- Review Field -->
<div class="col-sm-12">
    {!! Form::label('review', 'Review:') !!}
    <p>{{ $bracketStudent->review }}</p>
</div>

resources/views/bracket_students/table.blade.php
<div class="table-responsive">
    <table class="table" id="bracketStudents-table">
        <thead>
        <tr>
        <th>Academic Year Id</th>
        <th>Course Id</th>
        <th>Batch Id</th>
        <th>Bracket Id</th>
        <th>Teacher Id</th>
        <th>Subject Id</th>
        <th>Student Id</th>
        <th>Status</th>
        <th>Review</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($bracketStudents as $bracketStudent)
            <tr>
            <td>{{ $bracketStudent->academic_year_id }}</td>
            <td>{{ $bracketStudent->course_id }}</td>
            <td>{{ $bracketStudent->batch_id }}</td>
            <td>{{ $bracketStudent->bracket_id }}</td>
            <td>{{ $bracketStudent->teacher_id }}</td>
            <td>{{ $bracketStudent->subject_id }}</td>
            <td>{{ $bracketStudent->student_id }}</td>
            <td>{{ $bracketStudent->status }}</td>
            <td>{{ $bracketStudent->review }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['bracketStudents.destroy', $bracketStudent->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('bracketStudents.show', [$bracketStudent->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('bracketStudents.edit', [$bracketStudent->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>